### PR TITLE
Make demo work

### PR DESCRIPTION
**Pull request by cureforpain**
# Changes
- separate state for the Y
- applying theFunction asynchronous with useEffect that depends on X
# Preview

### CODE REVIEW

**Comment by cureforpain** [comment]
related to data-story-org/core#84

**Comment by cureforpain** [comment]
@ajthinking

**Comment by ajthinking** [comment]
```
± |Lenivaya-main ✓| → yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@data-story-org/core > laravel-mix@6.0.29" has unmet peer dependency "postcss@^8.3.1".
warning "@data-story-org/core > laravel-mix > autoprefixer@10.3.4" has unmet peer dependency "postcss@^8.1.0".
warning "@data-story-org/core > laravel-mix > cssnano@5.0.8" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > postcss-loader@6.1.1" has unmet peer dependency "postcss@^7.0.0 || ^8.0.1".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default@5.1.4" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > css-declaration-sorter@6.1.1" has unmet peer dependency "postcss@^8.0.9".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > cssnano-utils@2.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-calc@8.0.0" has unmet peer dependency "postcss@^8.2.2".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-colormin@5.2.0" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-convert-values@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-discard-comments@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-discard-duplicates@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-discard-empty@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-discard-overridden@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-merge-longhand@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-merge-rules@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-minify-font-values@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-minify-gradients@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-minify-params@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-minify-selectors@5.1.0" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-charset@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-display-values@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-positions@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-repeat-style@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-string@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-timing-functions@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-unicode@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-url@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-normalize-whitespace@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-ordered-values@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-reduce-initial@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-reduce-transforms@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-svgo@5.0.2" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-unique-selectors@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning "@data-story-org/core > laravel-mix > cssnano > cssnano-preset-default > postcss-merge-longhand > stylehacks@5.0.1" has unmet peer dependency "postcss@^8.2.15".
warning " > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
[1/7] ⠈ @data-story-org/core
[-/7] ⠈ waiting...
[3/7] ⠈ fsevents
[-/7] ⠈ waiting...
error /Users/anders/Code/x-to-y/node_modules/@data-story-org/core: Command failed.
Exit code: 1
Command: npm run build
Arguments:
Directory: /Users/anders/Code/x-to-y/node_modules/@data-story-org/core
Output:
npm WARN lifecycle The node binary used for scripts is /var/folders/9d/8n_tjc1x7pg3vxmqwnm5ml_40000gn/T/yarn--1631031513951-0.41244860075203027/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @data-story-org/core@0.0.3 build /Users/anders/Code/x-to-y/node_modules/@data-story-org/core
> tsc

sh: tsc: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @data-story-org/core@0.0.3 build: `tsc`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @data-story-org/core@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by cureforpain** [comment]
The thing here is that postinstall script depends on typescript compiler which is needed for transpilling core code. Best solution I see for now is to publish core on npm so it'll be already transpilled and ready to use as a dependency. I'll take care of adding publish scripts and release workflow.

**Comment by ajthinking** [comment]
> The thing here is that postinstall script depends on typescript compiler which is needed for transpilling core code. Best solution I see for now is to publish core on npm so it'll be already transpilled and ready to use as a dependency. I'll take care of adding publish scripts and release workflow.

Sounds like a good solution! Invited you to npmjs organisation data-story

**Comment by cureforpain** [comment]
@ajthinking, all installs without problems now

**Comment by ajthinking** [comment]
Perfect, thanks 🎉

**Pull request merged**
